### ISSUE TITLE
Job Page - Display Job

### ISSUE THREAD

**Issue by Krapil** [CS480Slackers/JobSearch#46]
For this to be implemented we need a container to get a job from the database.

For Roland: Can you make the page that displays the job?  
For now we just need to include the company, position, majors (array), location2 (this is an Address object, so can decide how you want to display the address fields like street and city, etc.), description, and externalURL fields.  

It can be barebones to start, as long as we have a link on our site that can display a job.

**Comment by roroadodo** [comment]
Decided against this feature
